title: Tomas Lukavec - Personal Website & Academic Blog
description: > # this means to ignore newlines until "baseurl:"
  Personal website & academic blog
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tomáš Lukavec # add your name
author-img: fotka.jpg # add your photo
about-author: Data Analyst & Ph.D. candidate # add description
social-twitter: TomLuk739 # add your Twitter handle
social-instagram: tom.lukavec # add your Facebook handle
social-linkedin: tomlukavec # add your Linkedin handle
social-email: tomas.lukavec{AT}fsv.cuni.cz # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]
